# Based on https://github.com/matrix-org/dendrite/blob/master/.github/workflows/docker-hub.yml

name: "Docker Hub - Release"

on:
  release:
    types: [published]

env:
  DOCKER_NAMESPACE: matrixdotorg
  PLATFORMS: linux/amd64

permissions:
  contents: read

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Get release tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/matrix-bifrost:${{ env.RELEASE_VERSION }}